#server:
#  port: 8080
#spring:
#  shardingsphere:
#    props:
#      sql:
#        show:
#          true
#    datasource:
#      names: ds1,ds2
#      ds1:
#        type: com.zaxxer.hikari.HikariDataSource
#        driverClassName: com.mysql.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Shanghai&useSSL=false
#        username: root
#        password: 123456
#      ds2:
#        type: com.zaxxer.hikari.HikariDataSource
#        driverClassName: com.mysql.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3306/shop2?serverTimezone=Asia/Shanghai&useSSL=false
#        username: root
#        password: 123456
#    sharding:
#      defaultDatabaseStrategy:
#        hint:
#          algorithmClassName: com.dgd.multidatasource.shardingsphere.MyDatasourceRoutingAlgorithm
#      tables:
#        shop_user:
#          actualDataNodes: ds1.shop_user
#        shop_order:
#          actualDataNodes: ds2.shop_order
#      defaultTableStrategy:
#        none:
#          any: ""
#
#mybatis:
#  mapper-locations: classpath*:/mappers/*.xml
